name: carubra-dashboard_client-doa
services:
  # ========================================
  # PRODUCTION ENVIRONMENT
  # ========================================
  node-carubra-dashboard-client_doa:
    build:
      context: .
      args:
        - ENV_FILE=.env
    container_name: carubra-dashboard-client_doa
    restart: always
    env_file:
      - .env
    networks:
      - carubra-network

  nginx-carubra-dashboard-client_doa:
    image: nginx:alpine
    container_name: nginx_proxy_client_doa
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-carubra-dashboard-client_doa
    networks:
      - carubra-network

networks:
  carubra-network:
    external: true