# Stage 1: Install dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package*.json ./
RUN npm install

# Stage 2: Build the application
FROM node:20-alpine AS builder
WORKDIR /app
ARG ENV_FILE=.env
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Menyalin file env spesifik menjadi standar Next.js .env.production saat build
COPY ${ENV_FILE} .env.production
ENV SUPABASE_SERVICE_ROLE_KEY=placeholder
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
ENV PORT 3003
# Next.js standalone requires hostname to be set to 0.0.0.0 to be accessible outside container
ENV HOSTNAME 0.0.0.0

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3003

CMD ["node", "server.js"]


