tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/${CLOUDFLARE_TUNNEL_ID}.json

ingress:
  - hostname: ${CLOUDFLARE_TUNNEL_HOSTNAME}
    service: http://nginx:80
  - service: http_status:404
